# Generated by Django 5.2.12 on 2026-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_order_discount_amount_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(blank=True, choices=[('CD', 'CD'), ('VINYL', 'Vinyl'), ('CASSETTE', 'Cassette'), ('MERCH', 'Merch'), ('GEAR', 'Gear')], max_length=20, null=True),
        ),
    ]
