# Generated by Django 5.2.12 on 2026-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='format',
            field=models.CharField(blank=True, choices=[('CD', 'CD'), ('VINYL', 'Vinyl'), ('CASSETTE', 'Cassette'), ('MERCH', 'Merch'), ('GEAR', 'Gear'), ('BY AC', 'By ArchClub'), ('SALE', 'Sale'), ('RESTOCK', 'Restock'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
